# VM Configuration lives here
module "vmss-1804acc" {
  source                                 = "modules/vmss-linux"
  vmscaleset_name                        = "1804acc"
  resource_group_name                    = "${var.resource_group_name}"
  cloudconfig_file                       = "${path.module}/cloud-init.tpl"
  location                               = "${var.location}"
  vm_size                                = "${var.vm_size_acc}"
  admin_username                         = "${var.oeadmin}"
  admin_password                         = "${var.oeadmin_password}"
  ssh_key                                = "~/.ssh/id_rsa.pub"
  nb_instance                            = "${var.nb_instance}"
  vm_os_publisher                        = "Canonical"
  vm_os_offer                            = "UbuntuServer"
  vm_os_sku                              = "18.04-LTS"
  vm_os_version                          = "latest"
  vnet_subnet_id                         = "${module.network-1804acc.vnet_subnets[0]}"
  load_balancer_backend_address_pool_ids = "${module.lb-1804acc.azurerm_lb_backend_address_pool_id}"
}

module "vmss-1604acc" {
  source                                 = "modules/vmss-linux"
  vmscaleset_name                        = "1604acc"
  resource_group_name                    = "${var.resource_group_name}"
  cloudconfig_file                       = "${path.module}/cloud-init.tpl"
  location                               = "${var.location}"
  vm_size                                = "${var.vm_size_acc}"
  admin_username                         = "${var.oeadmin}"
  admin_password                         = "${var.oeadmin_password}"
  ssh_key                                = "~/.ssh/id_rsa.pub"
  nb_instance                            = "${var.nb_instance}"
  vm_os_publisher                        = "Canonical"
  vm_os_offer                            = "confidential-compute-preview"
  vm_os_sku                              = "16.04-LTS"
  vm_os_version                          = "latest"
  vnet_subnet_id                         = "${module.network-1604acc.vnet_subnets[0]}"
  load_balancer_backend_address_pool_ids = "${module.lb-1604acc.azurerm_lb_backend_address_pool_id}"
}

module "vmss-1804nonacc" {
  source                                 = "modules/vmss-linux"
  vmscaleset_name                        = "1804nonacc"
  resource_group_name                    = "${var.resource_group_name}"
  cloudconfig_file                       = "${path.module}/cloud-init.tpl"
  location                               = "${var.location}"
  vm_size                                = "${var.vm_size}"
  admin_username                         = "${var.oeadmin}"
  admin_password                         = "${var.oeadmin_password}"
  ssh_key                                = "~/.ssh/id_rsa.pub"
  nb_instance                            = "${var.nb_instance}"
  vm_os_publisher                        = "Canonical"
  vm_os_offer                            = "UbuntuServer"
  vm_os_sku                              = "18.04-LTS"
  vm_os_version                          = "latest"
  vnet_subnet_id                         = "${module.network-1804nonacc.vnet_subnets[0]}"
  load_balancer_backend_address_pool_ids = "${module.lb-1804nonacc.azurerm_lb_backend_address_pool_id}"
}

module "vmss-2016acc" {
  source                                 = "modules/vmss-windows"
  vmscaleset_name                        = "2016acc"
  resource_group_name                    = "${var.resource_group_name}"
  cloudconfig_file                       = "${path.module}/cloud-init.tpl"
  location                               = "${var.location}"
  vm_size                                = "${var.vm_size_acc}"
  admin_username                         = "${var.oeadmin}"
  admin_password                         = "${var.oeadmin_password}"
  ssh_key                                = "~/.ssh/id_rsa.pub"
  nb_instance                            = "${var.nb_instance}"
  vm_os_publisher                        = "MicrosoftWindowsServer"
  vm_os_offer                            = "confidential-compute-preview"
  vm_os_sku                              = "acc-windows-server-2016-datacenter"
  vm_os_version                          = "latest"
  vnet_subnet_id                         = "${module.network-2016acc.vnet_subnets[0]}"
  load_balancer_backend_address_pool_ids = "${module.lb-2016acc.azurerm_lb_backend_address_pool_id}"
}

module "vmss-2016sgx" {
  source                                 = "modules/vmss-windows"
  vmscaleset_name                        = "2016sgx"
  resource_group_name                    = "${var.resource_group_name}"
  cloudconfig_file                       = "${path.module}/cloud-init.tpl"
  location                               = "${var.location}"
  vm_size                                = "${var.vm_size_acc}"
  admin_username                         = "${var.oeadmin}"
  admin_password                         = "${var.oeadmin_password}"
  ssh_key                                = "~/.ssh/id_rsa.pub"
  nb_instance                            = "${var.nb_instance}"
  vm_os_publisher                        = "MicrosoftWindowsServer"
  vm_os_offer                            = "confidential-compute-preview"
  vm_os_sku                              = "acc-windows-server-2016-datacenter"
  vm_os_version                          = "latest"
  vnet_subnet_id                         = "${module.network-2016sgx.vnet_subnets[0]}"
  load_balancer_backend_address_pool_ids = "${module.lb-2016sgx.azurerm_lb_backend_address_pool_id}"
}

module "vmss-2016nonsgx" {
  source                                 = "modules/vmss-windows"
  vmscaleset_name                        = "2016nonsgx"
  resource_group_name                    = "${var.resource_group_name}"
  cloudconfig_file                       = "${path.module}/cloud-init.tpl"
  location                               = "${var.location}"
  vm_size                                = "${var.vm_size}"
  admin_username                         = "${var.oeadmin}"
  admin_password                         = "${var.oeadmin_password}"
  ssh_key                                = "~/.ssh/id_rsa.pub"
  nb_instance                            = "${var.nb_instance}"
  vm_os_publisher                        = "MicrosoftWindowsServer"
  vm_os_offer                            = "confidential-compute-preview"
  vm_os_sku                              = "acc-windows-server-2016-datacenter"
  vm_os_version                          = "latest"
  vnet_subnet_id                         = "${module.network-2016nonsgx.vnet_subnets[0]}"
  load_balancer_backend_address_pool_ids = "${module.lb-2016nonsgx.azurerm_lb_backend_address_pool_id}"
}